component: http
name: noelle-nuxt3-sls
org: '1257818307'
app: noelle-web-prod
stage: prod
inputs:
  region: ap-chengdu
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
  faas:
    runtime: Nodejs16.13
    eip: false
    timeout: 3
    memorySize: 128
    tags: []
    framework: nuxtjs
    environments: []
    layers:
      - name: noelle-sls-layer
        version: 1
  apigw:
    timeout: 60
    protocols:
      - http
      - https
    environment: release
  isAutoCiDeploy: true
  codePlatform: GITHUB
  gitUrl: 'https://github.com/Genshin-Impact-Cult-of-Noelle/Noelle-Nuxt3-SLS.git'
  branch: main
