name: deploy serverless scf
on: 
  push:
    branches:
      - main 
jobs:
  deploy:
    name: deploy serverless scf
    runs-on: ubuntu-latest
    env: # 环境变量
          STAGE: prod #您的部署环境
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号 sercret ID，请在Settings-Secrets中配置
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号 sercret key，请在Settings-Secrets中配置
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: install dependency
        run: npm install
      - name: install serverless
        run: npm install -g serverless
      - name: build
        run: npm run build
      - name: deploy serverless
        run: sls deploy
        
